### ISSUE TITLE
Inspect cards

### ISSUE THREAD

**Issue by JeffSkyrunner** [dagguh/data-hunt#104]
**Is your feature request related to a problem? Please describe.**
I cannot understand which cards I have in hand/in play

**Describe the solution you'd like**
I would like to have something like "click/drag a specific icon/something" and have a big picture of the card.
For the PC version, maybe a standard "overlaying" action would be enough, while the mobile version might need a "on tap" event.

If we would like to have the same structure, maybe an "inspect mode" could be used, but I have the feeling this could slow down the game

**Additional context**

**Comment by dagguh** [comment]
Yeah, I imagine long-press could zoom in.
MTGA has this as right click, it's nice if you want to pause and read a card while they're flying around. And it's nice for stream/video watchers. It can show the big beautfiful art and big clear text.

**Comment by JeffSkyrunner** [comment]
Well, not only when they are flying around, also when they are in your hand... atm I have hard time in testing the game, since I don't recognize all the cards. :)
