### ISSUE TITLE
Find a way to show who is playing

### ISSUE THREAD

**Issue by JeffSkyrunner** [dagguh/data-hunt#105]
At the moment, there is no way to understand who is playing, if the corp or the runner

**Comment by dagguh** [comment]
You can _kinda_ tell by having only runner cards in hand and by having a runner id closeby, while on the other side of the board there are facedown corp cards (blue cardback) and the corp id faceup.
It could be more explicit though. Do you have a suggestion of a solution?

**Comment by JeffSkyrunner** [comment]
It can be something like MTG/Hearthstone, like highlighting the identity.

We could move the identity as it was an avatar (so in the middle part of the screen, under the cards in hand) so that we could both highlight who is playing and have more space for in play cards.

**Comment by JeffSkyrunner** [comment]
I think this can be closed now, with the background changing colors depending on turn's ownership...

**Comment by dagguh** [comment]
True, the day/night cycle from 1e9c5873a5dcdaa84c6a5d448248ec4b60ae8f61 *suggests* turn changes. It's not obvious, but let's see if playtest feedback will consider this a problem
