### ISSUE TITLE
Should Draw method in RD class have a check on not enough card available? 

### ISSUE THREAD

**Issue by JeffSkyrunner** [dagguh/data-hunt#96]
Am I missing something or we should alert somehow we haven't drawn enough cards?

public void Draw(int cards, Headquarters hq)
        {
            for (int i = 0; i < cards; i++)
            {
                if (HasCards())
                {
                    Zone.Cards[0].MoveTo(hq.Zone);
                }
            }
        }

**Comment by dagguh** [comment]
Good catch! That's definitely a gameplay bug.
It is a regression, because Corp decking out was handled before: 079825223f098b6362acd1d5c656afccf2a66a0a

**Comment by dagguh** [comment]
Interestingly, I did 079825223f098b6362acd1d5c656afccf2a66a0a to fix #24 a long time ago. I don't remember if the rules were like that or that Corp only had card draw via mandatory draw. But current CR 1.7.2.c clearly says:
> The Runner wins if the Corp is required to draw a card from R&D but cannot because R&D is empty.

So it should work for any draw, not only mandatory.
